spring.application.name=resume-ranking-system

spring.datasource.url=jdbc:mysql://localhost:3306/resume_ranker
spring.datasource.username=root
spring.datasource.password=Ruchitha@05
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

## If port 8080 is already in use on your machine, change this to another port.
server.port=8081